# Datos sacados de kaggle ( probabilidades de compra siendo mujer u hombre)


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("/Users/Acer/Desktop/Trabajos-subidos/Trabajos-por-hacer/gender-purchase/Gender Purchase.csv")
data

Gender Purchase
0    Female      Yes
1    Female      Yes
2    Female       No
3      Male       No
4      Male      Yes
..      ...      ...
506    Male      Yes
507  Female      Yes
508    Male       No
509  Female      Yes
510  Female      Yes

[511 rows x 2 columns]

In [4]:
#creamos una variable de contingencia para crusar filas y columnas

contigency_table = pd.crosstab(data["Gender"], data["Purchase"])
contigency_table

Purchase   No  Yes
Gender            
Female    106  159
Male      125  121

* Vemos que 106 mujeres NO compraron y 159 SI lo hicieron, mientras 125 Hombres no lo hicieron y 121 Si lo hicieron

In [6]:
contigency_table.sum(axis=1)

Gender
Female    265
Male      246
dtype: int64

* Cantidad de mujeres y hombres

In [7]:
contigency_table.sum(axis=0)

Purchase
No     231
Yes    280
dtype: int64

* Cantidad de "persona" que compro y no compro

In [9]:
contigency_table.astype("float").div(contigency_table.sum(axis=1),axis=0)*100

Purchase         No        Yes
Gender                        
Female    40.000000  60.000000
Male      50.813008  49.186992

* Porcentaje tanto de hombre o de mujeres de si compraron o no en la Web 
    * La probabilidad que una mujer compre es de 60% y del hombre un 49.18%

In [14]:
print("Probabilidad de que compre siendo HOMBRE")
print("%",121/246*100)

print("Probabilidad de que NO compre siendo HOMBRE")
print("%",125/246*100)

print("Probabilidad de que compre siendo MUJER")
print("%",159/265*100)

print("Probabilidad de que NO compre siendo MUJER")
print("%",106/265*100)

Probabilidad de que compre siendo HOMBRE
% 49.1869918699187
Probabilidad de que NO compre siendo HOMBRE
% 50.81300813008131
Probabilidad de que compre siendo MUJER
% 60.0
Probabilidad de que NO compre siendo MUJER
% 40.0


In [17]:
compra_h = 121/246
compra_m = 159/265

odds_h = compra_h/(1-compra_h)
odds_m = compra_m/(1-compra_m)

print("Ratio de compra siendo hombre =", odds_h)
print("Ratio de compra siendo mujer =", odds_m)

Ratio de compra siendo hombre = 0.9680000000000002
Ratio de compra siendo mujer = 1.4999999999999998


In [20]:
odds_ratio = odds_h/odds_m

odds_ratio1 = odds_m/odds_h

odds_ratio , odds_ratio1

(0.6453333333333335, 1.5495867768595035)

* Invertimos el denominador en ambas cuentas para saber quien tiene mayor Numero (mas propenso a tener exito) vemos que el mayor ratio lo tiene **la mujer = 1.54 y el hombre = 0.64**